Azure/alz-terraform-accelerator

bootstrap/azuredevops/providers.tf
bootstrap/azuredevops/variables.tf
bootstrap/github/providers.tf
bootstrap/github/variables.tf
docs/wiki/[User-Guide]-Quick-Start-Phase-2.md

Adds an `azure_subscription_id` variable that defaults to the connected subscription if left blank. This can be used to target a subscription other than the one connected to for the bootstrap resources.
A future iteration could update this field to use the `subscription_id_management` field in the starter module, but would require updates to the ALZ PowerShell module to achieve that in a robust way.
1. #15 
None. Defaults to the connected subscription if none is supplied, which is the existing behaviour.
Tested with this version of ALZ PowerShell module: https://github.com/Azure/ALZ-PowerShell-Module/pull/77

feature: subscription override field

---

bootstrap/azuredevops/variables.tf
bootstrap/github/variables.tf
bootstrap/modules/azure_devops/locals.tf
bootstrap/modules/github/locals.tf
docs/wiki/[User-Guide]-Quick-Start-Phase-2.md

Adding the ability to override SaaS hosted GitHub and Azure DevOps with a self-hosted VCS url. 
NOTE: This is not something we can test and some features, such as Workload identity federation will not work with self hosted yet.
1. #13 
None

feature: support self hosted vcs

---

.gitignore
docs/wiki/[User-Guide]-Quick-Start-Phase-1.md

This pull request fixes an issue in the docs where the root account is not granted enough permissions to apply roles on the management groups.
1. #44 
1. None
Replicated the issue locally with an SP, elevated the SP and it worked.

docs: update permissions in the docs

---

templates/ci_cd/github/cd.yaml
templates/ci_cd/github/ci.yaml
templates/ci_cd/github/templates/ci.yaml

This PR fixes a reported bug with GitHub actions permissions.
The reason we have to set the `environment` in the validation job is due to known bug in GitHub. If you alter the token subject to specify environment, then any jobs under the scope of the `id-token: write` permission that do not have an environment cause the pipeline to immediately bomb out with an unexpected error and no details. This has been reported to GitHub and they have replicated it, but we need to have the workaround for now. In this use case it does not cause any security issue.
1. #53 
1. None
Run an end to end test with the lowered action permissions set on the org.

bug fix for pipeline permissions

---

templates/complete/config.yaml
templates/complete/locals.tf
templates/complete/main.tf

1. https://github.com/Azure/alz-terraform-accelerator/issues/65

fix: complete starter module conditional error

---

docs/wiki/[User-Guide]-Quick-Start-Phase-2-Azure-DevOps.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-GitHub.md
docs/wiki/[User-Guide]-Quick-Start-Phase-2-Local.md
templates/hubnetworking/variables.tf

Minor typo found in templates/hubnetworking/variables.tf during testing, foe changed to for.
1. Changes foe to for in templates/hubnetworking/variables.tf for 2 x variables.
2. Adds additional advice into 3 x quick start guides which for step 1 adding in E.g. `basic` , `hubnetworking` or `complete`. in local, GitHub, and DevOps guides. Also updating a couple of minor typos.
1. N/A
None required as these are just spelling updates to var and ReadMe files.

Minor typo in hub var.tf and Recommendation to Quick Start content

---

templates/ci_cd/azuredevops/templates/cd.yaml
templates/ci_cd/azuredevops/templates/ci.yaml

The default timeout of 60 minutes can sometimes be breached due to the nature of the ALZ modules
N/A
None
e2e tests run

enhancment: set azure devops timeout to max

---

docs/wiki/[User-Guide]-Quick-Start-Phase-1-Service-Principal.md

When adding a role assignment, the conditions tab has an option next to "What user can do", which is now required for highly privileged roles, such as Owner
1. Updated the Service Principal user guide, under the "Create Permissions" section, to reflect the required option for assigning privileged roles
1. N/A
Change to the User-guide for Service Principal role assignment, tested on fork to ensure the text reads correctly
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
- [ x] Performed testing and provided evidence.
- [ x] Updated relevant and associated documentation.

Added new condition option, for SPN role assignment which is now required

---

templates/complete_multi_region/networking-hub-and-spoke-vnet.tf

Resolve a reported race condition when vnet gateway and firewall deploy at the same time.
N/A
None

fix: vnet gateway firewall race condition

---

.gitignore
templates/.config/ALZ-Powershell.config.json
templates/complete_multi_region/variables-connectivity.tf
templates/hubnetworking/variables.tf
templates/test/terraform.tf
templates/test_nested/modules/test_module/main.tf
templates/test_nested/modules/test_module/outputs.tf
templates/test_nested/modules/test_module/terraform.tf
templates/test_nested/modules/test_module/variables.tf
templates/test_nested/test_root/README.md
templates/test_nested/test_root/main.tf
templates/test_nested/test_root/outputs.tf
templates/test_nested/test_root/terraform.tf
templates/test_nested/test_root/variables.tf
templates/test_nested/test_to_remove/README.md
templates/test_nested/test_to_remove/main.tf
templates/test_nested/test_to_remove/outputs.tf
templates/test_nested/test_to_remove/terraform.tf
templates/test_nested/test_to_remove/variables.tf

Add submodule support for starter modules
N/A
N/A
e2e tests running here: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/11487105261

feat: add starter submodule support

---

templates/complete/main.tf
templates/complete_multi_region/modules/management-es/main.tf

Updating the default value of `strict_subscription_association` to `false`
1. This change will allow to provision subscriptions outside of the ALZ accelerator and will not remove during the apply.

Update the `strict_subscription_association` default value to false

---

templates/microsoft_cloud_for_industry/financial_services_landing_zone/locals.tf
templates/microsoft_cloud_for_industry/sovereign_landing_zone/locals.tf

1. Update exemptions to fix policy assignments.
1. Need to destroy existing exemptions first. They redeploy the new exemptions.

Update exemptions to fix policy assignments.

---

.github/workflows/end-to-end-test.yml
templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
templates/platform_landing_zone/examples/management-only/management.tfvars
templates/platform_landing_zone/modules/management_groups/locals.tf
templates/platform_landing_zone/modules/management_groups/main.tf

This PR moves all custom resource names into the same section to simplify usage
N/A
None

feat-standardise-naming

---

templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars

Replace the default naming convention for the Bastion host.
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/270
None

fix: bastion host default naming convention

---

templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
templates/platform_landing_zone/examples/management-only/management.tfvars
templates/platform_landing_zone/modules/management_groups/locals.tf
templates/platform_landing_zone/modules/management_groups/main.tf

Fixes a potential issue with role assignment timing.
Removes the `architecture_name` from the exmaple config to avoid further user confusion.
N/A
None

fix: role assignment timing issue

---

templates/platform_landing_zone/modules/virtual-wan/locals.firewall.tf

Fix an issue with private DNS resolver IP with VWAN when DNS is disabled
N/A
None

fix: vwan no dns

---

templates/platform_landing_zone/modules/management_resources/main.tf

Turn off the automation account by default to follow ALZ guidance
None
The plan will destroy the automation account if it already exists. You can turn it back on in config if you beleive you need it.

feat: turn off automation account by default

---

templates/platform_landing_zone/locals.tf
templates/platform_landing_zone/variables.tf

The validation for `starter_locations `within the platform landing zone fails when `connectivity_type` is set to `none`. These validation changes were introduced in PR #225.
The issue arises because the validation logic still assesses `var.virtual_wan_virtual_hubs` and `var.hub_and_spoke_vnet_virtual_networks`, even though these variables are not supplied when `connectivity_type` is `none`.

fix: Support for management-only scenario

---

templates/platform_landing_zone/examples/full-multi-region-nva/README.md
templates/platform_landing_zone/examples/full-multi-region/README.md
templates/platform_landing_zone/examples/full-single-region-nva/README.md
templates/platform_landing_zone/examples/full-single-region/README.md
templates/platform_landing_zone/examples/management-only/README.md

For some reason the URL to the Azure Landing Zones documentation site in all of the example `README` files points to a financial institution and not a Microsoft owned website. For simplicity I have just updated the urls to use https://azure.github.io/Azure-Landing-Zones/accelerator/startermodules/terraform-platform-landing-zone/scenarios/ where an overview of all the scenarios are listed
1. Faulty URLs in `README` files
not applicable. This pr doesn't touch any code

docs: update url in example readmes

---

templates/platform_landing_zone/modules/management_groups/main.tf

Fixes bug with policy role assignments for the [Configure Azure Machine Learning workspace to use private DNS zones](https://www.azadvertizer.net/azpolicyadvertizer/ee40564d-486e-4f68-a5ca-7a621edae0fb.html) policy.

chore: bump alz pattern module to 0.12.3

---

templates/platform_landing_zone/main.connectivity.virtual.wan.tf

Support plural delegations variable in vnet module
Related: https://github.com/Azure/terraform-azurerm-avm-ptn-alz-connectivity-virtual-wan/issues/33

feat: plural delegations support
