- README.md
Update the warning on the read in preparation for wider communication.
N/A
N/A
N/A
> chore-update-readme-warning

- tests/scripts/get-release.ps1
Update for change to parameter in ALZ PowerShell and ensure E2E tests continue to run.
N/A
None
PR tests will pass.
> chore: update e2e tests to work with alz powershell update

- docs/wiki/Contributing-to-Documentation.md
- docs/wiki/Home.md
- docs/wiki/[User-Guide]-Quick-Start-Phase-1.md
- docs/wiki/[User-Guide]-Quick-Start-Phase-2.md
- docs/wiki/[User-Guide]-Quick-Start-Phase-3.md
> Docs: Remove spelling errors and improve readability 

- templates/ci_cd/azuredevops/templates/cd.yaml
- templates/ci_cd/github/templates/cd.yaml
The artefacts were missing lock and yaml files. This PR updates the filter to be exclusive rather than inclusive, so it will support any starter module.
N/A
None
> bug: missing artefact files

- bootstrap/azuredevops/main.tf
- bootstrap/modules/azure_devops/extension-install.ps1
- bootstrap/modules/azure_devops/extension.tf
- bootstrap/modules/azure_devops/variables.tf
- docs/wiki/[User-Guide]-Quick-Start-Phase-1.md
This PR ensures that the DevLabs task is installed. If already installed it will continue. If it fails to install it will fail.
1. #37 
1. None
Tested locally and run e2e tests
> feature: add provisioner for devlabs task

- .github/workflows/end-to-end-test.yml
Updates the end to end tests for provide more comprehensive coverage of Terraform CLI install and upgrade process with ALZ PowerShell module
N/A
None
End to end tests should pass.
> chore: e2e tests validate the alz module installs latest terraform or upgrades 1.5

- templates/complete/main.tf
- templates/complete/variables.tf
> fix: add validation type to `complete/variables.tf`

- templates/complete/config.yaml
> fix: temporarily disable telemetry for default `config.yaml`

- docs/wiki/[User-Guide]-Starter-Module-Complete.md
- docs/wiki/[User-Guide]-Starter-Modules.md
- docs/wiki/[User-Guide]-YAML-Schema-Reference.md
- docs/wiki/_Sidebar.md
> docs: add docs for `complete` starter module

- docs/wiki/_Sidebar.md
Rogue character in docs side bar.
> Fix typo in docs

- README.md
- docs/wiki/[User-Guide]-Quick-Start-Phase-2-Local.md
Remove the warning message for the `local` option.
> docs: remove warnings and tidy read me

- README.md
The third party badges in the read me are inaccurate, so will be removed.
> dics: remove badges that no longer work

- docs/wiki/Troubleshooting.md
Based on feedback from ALZ team, add some trouble shooting advice for ALZ PowerShell module version issues.
1. #86 
None, docs only
Docs only
> docs: add trouble shooting for ALZ module

- templates/hubnetworking/main.tf
> fix: add depends_on `hubnetworking`

- .github/workflows/wiki-sync.yml
> chore: wiki-sync.yml perms

- templates/basic/main.tf
Make the module name consistent across CAF
1. #106 
1. Basic module update would result in a destroy and create. This can be overcome by adding a moved block.
> chore: Bring module names in line

- .github/workflows/end-to-end-test.yml
- templates/ci_cd/azuredevops/templates/helpers/terraform-init.yaml
When using a Microsoft-hosted agent the run fails
1. #108 
1. None
e2e tests run
> bug: init fails for Microsoft-hosted agent in Azure DevOps

- docs/wiki/Upgrade-Guide.md
Fix note in docs
N/A
None
Docs only
> branch protection note update

- docs/wiki/Upgrade-Guide.md
Further enhance upgrade docs
N/A
None  
Docs only
> Update upgrade docs

- .gitignore
- templates/complete_vnext/data.tf
- templates/complete_vnext/locals.tf
- templates/complete_vnext/main.tf
- templates/complete_vnext/outputs.tf
Fix up the vnext module to support the latest version
None
Only for vNext which is not supported yet
Run locally
> enhancement: update for latest version of vnext

- docs/wiki/examples/starter-module-config/complete/config-hub-spoke.yaml
- docs/wiki/examples/starter-module-config/complete/config-vwan.yaml
Fix for a change to the upstream CAF module
N/A
None
Docs only
> docs: fix examples for upstream changes

- docs/wiki/[User-Guide]-Quick-Start-Phase-1.md
Wording was legacy, referencing Microsoft internal literature. This makes it appropriate for public consumption.
I have just reworded some of the getting started guide so that it is appropriate for public consumption. It currently contains a Microsoft internal reference which may be confusing. I believe this was leftover from the initial hackathon for testing this accelerator a few generations ago. 
1. Wording from referencing Microsoft specific "MCAPS External Subscription", to a generalised version suitable for public consumption. 
1. None.
- [N/A] Associated it with relevant [issues](https://github.com/Azure/alz-terraform-accelerator/issues), …
> Reworded "Set up billing" to consumer/customer appropriate

- docs/wiki/examples/powershell-inputs/inputs-azure-devops.yaml
Fix typo in the inputs example file
1. https://github.com/Azure/alz-terraform-accelerator/issues/138
None
Docs only
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [ x] Associated it with relevant [issues](https://github.com/Azure/alz-terraform-accelerator/issues), for tracking and closure.
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
- [ x] Performed testing and provided evidence.
- [ x] Updated relevant and associated documentation.
> docs: update inputs-azure-devops.yaml

- templates/complete/main.tf
- templates/complete_vnext/main.tf
> Update vwan properties

- .github/workflows/release.yml
> improve pipeline

- .github/workflows/release.yml
> tidy action

- .github/workflows/release.yml
> Update archive path

- templates/.config/ALZ-Powershell.config.json
> Add short name config

- .github/workflows/release.yml
> Fix artifact spelling

- .github/workflows/release.yml
> Update to use release created trigger

- templates/test/main.tf
- templates/test/terraform.tf
Add azapi to e2e tests
N/A
None
> Update test to include azapi

- templates/test/main.tf
> Remove schema valdation  for rg

- .github/workflows/scorecard.yml
- templates/basic/main.tf
- templates/basic/terraform.tf
- templates/complete/main.tf
- templates/complete/terraform.tf
- templates/hubnetworking/main.tf
- templates/hubnetworking/terraform.tf
Update to target v6 of the CAF module
N/A
See CAF module release notes
> upgrade to v6 of CAF module

- templates/basic/main.tf
- templates/basic/variables.tf
- templates/complete/config.yaml
- templates/complete/locals.tf
- templates/complete/main.tf
- templates/complete/variables.tf
- templates/hubnetworking/main.tf
- templates/hubnetworking/variables.tf
- templates/test/main.tf
- templates/test/variables.tf
> Fix variable name to match latest ALZ PS module mapping

- .github/workflows/release.yml
Fixes the trigger for publishing release artifacts
N/A
N/A
> chore: fix trigger for artifacts

- templates/complete_multi_region/examples/config-hub-and-spoke-vnet-multi-region.tfvars
- templates/complete_multi_region/examples/config-virtual-wan-multi-region.tfvars
- templates/complete_multi_region/modules/hub-and-spoke-vnet/main.tf
- templates/complete_multi_region/modules/virtual-wan/main.tf
Fix a few places where we missed setting telemetry and tags.
N/A
None
> fix: missing tags and telemetry

- templates/complete_multi_region/modules/hub-and-spoke-vnet/main.tf
- templates/complete_multi_region/modules/virtual-wan/main.tf
- templates/microsoft_cloud_for_industry/sovereign_landing_zone/main.platform.tf
Update Private Link DNS Zones module to `v0.5.0`
1. Update Private Link DNS Zones module to `v0.5.0`
None
> Update pdns module

- templates/platform_landing_zone/modules/management_groups/locals.tf
- templates/platform_landing_zone/modules/management_groups/main.tf
Add retries for policy definitions
None
None
> feat: policy definition retries

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/management-only/management.tfvars
Remove duplicate defender plan parameter
N/A
None
> fix: remove duplicate defender plan

- templates/microsoft_cloud_for_industry/financial_services_landing_zone/examples/bootstrap/inputs-azure-devops.yaml
- templates/microsoft_cloud_for_industry/financial_services_landing_zone/examples/bootstrap/inputs-github.yaml
- templates/microsoft_cloud_for_industry/financial_services_landing_zone/examples/bootstrap/inputs-local.yaml
- templates/microsoft_cloud_for_industry/sovereign_landing_zone/examples/bootstrap/inputs-azure-devops.yaml
- templates/microsoft_cloud_for_industry/sovereign_landing_zone/examples/bootstrap/inputs-github.yaml
- templates/microsoft_cloud_for_industry/sovereign_landing_zone/examples/bootstrap/inputs-local.yaml
Fix missing config for SLZ / FSI
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/267
None
> fix: missing slz fsi input

- templates/platform_landing_zone/terraform.tf
- templates/platform_landing_zone/variables.connectivity.virtual.wan.tf
Add missing vwan gateway setting.
This also pins the library version to avoid unexpected updates.
None
None
> fix: missing vwan gateway variable

- templates/platform_landing_zone/variables.connectivity.virtual.wan.tf
Make it so that each region can define different gateways
N/A
None
> fix: optional-gateways-for-vwan

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/management-only/management.tfvars
Move the email security contact to the top of the config since it is the only thing that has to be changed
N/A
N/A
> fix: move email security contact to top

- templates/platform_landing_zone/modules/management_groups/locals.tf
Increase timeouts to help with ADO eventual consistency issue
1. https://github.com/Azure/terraform-azurerm-avm-ptn-alz/issues/157
2. https://github.com/Azure/ALZ-PowerShell-Module/issues/269
None
> Increase timeouts

- templates/platform_landing_zone/modules/management_groups/locals.tf
Fix an issue where permissions have not yet propogated from the accelerator bootstrap
N/A
None
> fix: root management group permissions issue

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/management-only/management.tfvars
Match the updated management group id
None
None
> fix: defender management group name

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/management-only/management.tfvars
Turn telemetry on by default for GA
N/A
None
> chore: turn telemetry on by default

- templates/platform_landing_zone/lib/alz_library_metadata.json
- templates/platform_landing_zone/terraform.tf
Ensure library versin is in a single place
N/A
None
> fix: library version

- templates/platform_landing_zone/modules/hub-and-spoke-vnet/locals.dns.tf
- templates/platform_landing_zone/modules/virtual-wan/locals.dns.tf
Fixes a bug when removing the private DNS block from config
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/289
None
> fix: turn off private dns

- templates/platform_landing_zone/modules/management_groups/main.tf
Add policy role assignment override fields for advanced use cases
N/A
None
> feat: add policy assignment role assignment override variables

- templates/platform_landing_zone/lib/alz_library_metadata.json
Update library version for broken policy 
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/301
Policy set definition will be replaced, but is not assigned by default.
> feat: update library version

- .gitignore
- templates/platform_landing_zone/modules/hub-and-spoke-vnet/locals.firewall.tf
- templates/platform_landing_zone/modules/hub-and-spoke-vnet/locals.tf
- templates/platform_landing_zone/modules/hub-and-spoke-vnet/outputs.tf
- templates/platform_landing_zone/modules/virtual-wan/main.tf
- templates/platform_landing_zone/modules/virtual-wan/outputs.tf
- templates/platform_landing_zone/outputs.tf
* Add additional outputs for connectivity.
* Refactor firewall policy DNS to allow overriding and support Basic SKU
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/297
2. https://github.com/Azure/ALZ-PowerShell-Module/issues/307
None
> feat: additional outputs

- templates/platform_landing_zone/main.connectivity.virtual.wan.tf
- templates/platform_landing_zone/outputs.tf
Update vwan module to include bug fixes
N/A
Outputs renamed
> feat: update vwan module

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/management-only/management.tfvars
- templates/platform_landing_zone/modules/management_groups/main.tf
Update the management group module to support management group role assignments
N/A
None
> feat: management group role assignments

- templates/platform_landing_zone/modules/config-templating/outputs.tf
- templates/platform_landing_zone/outputs.tf
Output all templated inputs, so they can be used in upstream modules by customers if needed.
N/A
None
> feat: output templated inputs

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/main.connectivity.hub.and.spoke.virtual.network.tf
- templates/platform_landing_zone/main.connectivity.virtual.wan.tf
- templates/platform_landing_zone/main.resource.groups.tf
- templates/platform_landing_zone/modules/config-templating/locals.config.tf
- templates/platform_landing_zone/modules/config-templating/locals.connectivity.hub.and.spoke.virtual.network.tf
- templates/platform_landing_zone/modules/config-templating/locals.connectivity.virtual.wan.tf
- templates/platform_landing_zone/modules/config-templating/locals.management.tf
- templates/platform_landing_zone/modules/config-templating/locals.resource.groups.tf
- templates/platform_landing_zone/modules/config-templating/locals.tags.tf
- templates/platform_landing_zone/modules/config-templating/variables.tf
- templates/platform_landing_zone/variables.connectivity.tf
Simplify the provisioning decision for connectivity resources by bring them to the top section and having one setting to control the resource and resource group.
N/A
None
> feat: add connectivity provisioning section

- templates/platform_landing_zone/main.connectivity.virtual.wan.tf
- templates/platform_landing_zone/outputs.tf
Fix vwan defasult tags and add express route output for vwan
N/A
None
> fix: vwan default tags

- templates/platform_landing_zone/examples/full-multi-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-multi-region/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/virtual-wan.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
- templates/platform_landing_zone/modules/management_groups/main.tf
Updates to support migration
None
N/A
> feat: updates for migration

- .github/workflows/release.yml
Releaser broken, temporary fix to use older task version.
Issue: https://github.com/softprops/action-gh-release/issues/628
> fix: release bug

- templates/platform_landing_zone/examples/full-single-region/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region/virtual-wan.tfvars
Minor typo and wording fix in the examples
Minor typo and wording fix in the examples
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
> Minor typo and wording updates

- templates/platform_landing_zone/examples/full-multi-region-nva/hub-and-spoke-vnet.tfvars
- templates/platform_landing_zone/examples/full-single-region-nva/hub-and-spoke-vnet.tfvars
Add missing vnet gateway parent_id for NVA example config
N/A
None
> fix: nva examples virtual network gateway parent_id

- .github/workflows/release.yml
Added a step to check for valid Git references before release. Fail the build if it is not a tag.
N/A
None
> Add Git ref validation step in release workflow

- templates/platform_landing_zone/lib/alz_library_metadata.json
Built in policy has changed the allowed input parameter values
N/A
None
> fix: built in policy issue
